# src/OC/CoreBundle/Resources/config/routing.yml
#  UTF-8 sans BOM

# mapping des routes
# src/OC/CoreBundle/Resources/config/routing.yml

oc_core_home:
    path:     /
    defaults: 
        _controller: CoreBundle:Core:index

oc_core_contact:
    path:     /contact
    defaults: 
        _controller: CoreBundle:Core:contact
